<?php
require_once __DIR__ . '/../../vendor/autoload.php'; // Dompdf autoload
require_once __DIR__ . '/../../includes/config.php';
require_once __DIR__ . '/../../includes/functions.php';
require_once __DIR__ . '/../../classes/Report.php';

use Dompdf\Dompdf;

// Get filters
$startDate = $_POST['start'] ?? $_GET['start'] ?? date('Y-m-01');
$endDate = $_POST['end'] ?? $_GET['end'] ?? date('Y-m-d');
$tab = $_POST['tab'] ?? $_GET['tab'] ?? 'users';

$report = new Report();
$reportData = $report->generateSystemReport($startDate, $endDate);

// Get detailed data for the selected tab
if ($tab === 'users') {
    $tableData = $report->getUserReportData($startDate, $endDate);
    $tableHeaders = ['ID', 'Name', 'Email', 'Role', 'Status', 'Joined'];
    
    // Process the data to handle both naming conventions
    foreach ($tableData as &$row) {
        // Create a new row with standardized keys
        $processedRow = [
            'id' => $row['userId'] ?? $row['user_id'] ?? 'N/A',
            'name' => ($row['firstName'] ?? $row['first_name'] ?? 'Unknown') . ' ' . ($row['lastName'] ?? $row['last_name'] ?? 'User'),
            'email' => $row['email'] ?? 'N/A',
            'role' => ucfirst($row['userType'] ?? $row['user_type'] ?? 'Unknown'),
            'status' => ucfirst($row['status'] ?? 'Unknown'),
            'joined' => date('M j, Y', strtotime($row['createdAt'] ?? $row['created_at'] ?? 'now'))
        ];
        $row = $processedRow;
    }
} elseif ($tab === 'jobs') {
    $tableData = $report->getJobReportData($startDate, $endDate);
    $tableHeaders = ['ID', 'Title', 'Company', 'Type', 'Location', 'Applications', 'Status', 'Posted'];
} else {
    $tableData = $report->getCompanyReportData($startDate, $endDate);
    $tableHeaders = ['ID', 'Name', 'Industry', 'Size', 'Location', 'Contact', 'Active Jobs', 'Registered'];
}

// Prepare logo as base64
$logoPath = __DIR__ . '/../../assets/images/V5NR.png';
$logoData = '';
if (file_exists($logoPath)) {
    $logoType = pathinfo($logoPath, PATHINFO_EXTENSION);
    $logoBase64 = base64_encode(file_get_contents($logoPath));
    $logoData = 'data:image/' . $logoType . ';base64,' . $logoBase64;
}

// Prepare chart as base64
$chartUrl = 'https://quickchart.io/chart?c={type:\'line\',data:{labels:[\'Mon\',\'Tue\',\'Wed\',\'Thu\',\'Fri\',\'Sat\',\'Sun\'],datasets:[{label:\'Signups\',data:[12,19,3,5,2,3,7]}]}}';
$chartData = '';
$chartImage = @file_get_contents($chartUrl);
if ($chartImage !== false) {
    $chartData = 'data:image/png;base64,' . base64_encode($chartImage);
}

// Prepare HTML for PDF
$html = '';
if ($logoData) {
    $html .= '<div style="text-align:center;margin-bottom:10px;"><img src="' . $logoData . '" alt="Logo" style="height:60px;"></div>';
}
$html .= '<h1 style="color:#2a5bd7;text-align:center;margin-bottom:0;">System Report</h1>';
$html .= '<p style="text-align:center;margin-top:0;font-size:14px;">Generated by JOBEST Admin Panel</p>';
$html .= '<hr style="margin:10px 0 20px 0;">';
$html .= '<h2 style="font-size:18px;">Summary</h2>';
$html .= '<ul style="font-size:14px;">';
$html .= '<li><strong>Report Period:</strong> ' . htmlspecialchars($startDate) . ' to ' . htmlspecialchars($endDate) . '</li>';
$html .= '<li><strong>Total Signups:</strong> ' . number_format($reportData['total_signups']) . '</li>';
$html .= '<li><strong>Total Job Postings:</strong> ' . number_format($reportData['total_job_postings']) . '</li>';
$html .= '<li><strong>Total Applications:</strong> ' . number_format($reportData['total_applications']) . '</li>';
$html .= '<li><strong>Total Companies:</strong> ' . number_format($reportData['total_companies']) . '</li>';
$html .= '</ul>';
$html .= '<p style="font-size:13px;">This report provides an overview of system activity and detailed data for the selected section below.</p>';

// Add the chart image if available
$html .= '<h2 style="font-size:16px;">User Activity (Sample Chart)</h2>';
if ($chartData) {
    $html .= '<div style="text-align:center;"><img src="' . $chartData . '" style="width:100%;max-width:500px;"></div>';
} else {
    $html .= '<div style="width:100%;max-width:500px;height:300px;border:2px solid #888;text-align:center;line-height:300px;color:#888;margin:0 auto;">Chart unavailable</div>';
}

// Add detailed table
$html .= '<h2 style="margin-top:30px;font-size:16px;">Detailed ' . ucfirst($tab) . ' Data</h2>';
$html .= '<table border="1" cellpadding="5" cellspacing="0" width="100%" style="border-collapse:collapse;font-size:12px;">';
$html .= '<tr style="background:#f8f9fa;">';
foreach ($tableHeaders as $header) {
    $html .= '<th>' . htmlspecialchars($header) . '</th>';
}
$html .= '</tr>';
foreach ($tableData as $row) {
    $html .= '<tr>';
    foreach ($row as $cell) {
        $html .= '<td>' . htmlspecialchars(is_null($cell) ? '' : $cell) . '</td>';
    }
    $html .= '</tr>';
}
$html .= '</table>';

// Create Dompdf instance
$dompdf = new Dompdf();
$dompdf->loadHtml($html);
$dompdf->setPaper('A4', 'portrait');
$dompdf->render();
$dompdf->stream('system-report.pdf', ['Attachment' => true]);
exit; 